/*
 * @Description  : 步进电机控制实现
 * @Author       : FZU Liao
 * @Date         : 2022-01-03 15:48:25
 * @LastEditors  : Liao
 * @LastEditTime : 2022-01-11 09:58:22
 * @FilePath     : \TEMPLATE_PROJECT\CODES\DRIVER\STEP_MOTOR.c
 * Copyright 2022 FZU Liao, All Rights Reserved. 
 */

#include "STEP_MOTOR.h"
#include "DELAY.h"

void STEP_MOTOR_INIT(STEP_MOTOR* MOTOR,PWM_CHANNEL_enum MOTOR_PWM_CHANNEL){
    MOTOR->MOTOR_PWM_CHANNEL = MOTOR_PWM_CHANNEL;
    PWM_INIT_PWMCHANNEL(MOTOR_PWM_CHANNEL,12500,0);
    PWM_ENABLE(MOTOR_PWM_CHANNEL);
}

void STEP_MOTOR_SET_DUTY(STEP_MOTOR* MOTOR,uint16 Duty){
    PWM_SET_DUTY(MOTOR->MOTOR_PWM_CHANNEL,Duty);
}

void STEP_MOTOR_FORWARD(STEP_MOTOR* MOTOR){
    PWM_ENABLE(MOTOR->MOTOR_PWM_CHANNEL);
}

void STEP_MOTOR_STOP(STEP_MOTOR* MOTOR){
    PWM_DISABLE(MOTOR->MOTOR_PWM_CHANNEL);
}

void STEP_MOTOR_BACK(STEP_MOTOR* MOTOR){
    PWM_DISABLE(MOTOR->MOTOR_PWM_CHANNEL);
}

STEP_MOTOR_STATUS STEP_MOTOR_READ_STATUS(STEP_MOTOR* MOTOR){
    return MOTOR->STATUS;
}

uint32 STEP_MOTOR_GET_DUTY(STEP_MOTOR* MOTOR){
    return MOTOR->MOTOR_PWM_Duty;
}